name: mobnewharvest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+4
  path_provider: ^2.0.8
  http: ^0.13.6
  signature: ^5.4.0 
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.3
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_completo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_completo.jpg"
  adaptative_icon_foreground_inset: 24

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_completo.jpg